server {
    listen 80;
    server_name _;
    root /var/www/html/public;

    location = / {
        rewrite ^ /cockpit.html last;
    }

    location ~* \.(html|css|js|ico|png|jpg|jpeg|gif|svg|woff2?)$ {
        try_files $uri =404;
        expires 1d;
    }

    location / {
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
    }
}
